<a href="https://colab.research.google.com/github/rangeethasajeer-debug/CSCN8000-lab-submissions/blob/main/students-submissions/9081357/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB1 -Notebook to Demonstrate NumPy Operations**

# **Part A**

## 2.Create an array that starts at integer 1 ,ends at 20 and increments by 3



In [11]:
import numpy as np

array_result = np.arange(1, 21, 3)
print(array_result)

[ 1  4  7 10 13 16 19]


## 3.Create a new array of shape 3 with random numbers between 0 & 1

In [12]:

random_array = np.random.rand(3)
print(random_array)

[0.34325605 0.90087694 0.37112742]


## 4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
     
###   Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [15]:


#Create the 2D array
array_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("Original 2D Array:\n", array_2d)

#Slice the 2D array to get the first 2 rows
first_two_rows = array_2d[:2, :]
print("\nFirst two rows:\n", first_two_rows)

#Slice the 2D array to get the last 2 rows
last_two_rows = array_2d[1:, :]
print("\nLast two rows:\n", last_two_rows)

Original 2D Array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows:
 [[10 20 45]
 [30 12 16]]

Last two rows:
 [[30 12 16]
 [42 17 56]]


## 5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [16]:


#create two 2x2 arrays
array1 = np.array([[10, 20], [30, 40]])
array2 = np.array([[50, 60], [70, 80]])

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

#Vertical stacking
v_stacked_array = np.vstack((array1, array2))
print("\nVertically Stacked Array:\n", v_stacked_array)

#Horizontal stacking
h_stacked_array = np.hstack((array1, array2))
print("\nHorizontally Stacked Array:\n", h_stacked_array)

#Split the vertically stacked arrays in to two original 2x2 arrays
split_v_arrays = np.split(v_stacked_array, 2)
print("\nSplitting Vertically Stacked Array (array1, array2):\n")
print("Split Array 1:\n", split_v_arrays[0])
print("Split Array 2:\n", split_v_arrays[1])

#Split the horizontally stacked arrays into two original 2x2 arrays
split_h_arrays = np.hsplit(h_stacked_array, 2)
print("\nSplitting Horizontally Stacked Array (array1, array2):\n")
print("Split Array 1:\n", split_h_arrays[0])
print("Split Array 2:\n", split_h_arrays[1])







Array 1:
 [[10 20]
 [30 40]]

Array 2:
 [[50 60]
 [70 80]]

Vertically Stacked Array:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]

Horizontally Stacked Array:
 [[10 20 50 60]
 [30 40 70 80]]

Splitting Vertically Stacked Array (array1, array2):

Split Array 1:
 [[10 20]
 [30 40]]
Split Array 2:
 [[50 60]
 [70 80]]

Splitting Horizontally Stacked Array (array1, array2):

Split Array 1:
 [[10 20]
 [30 40]]
Split Array 2:
 [[50 60]
 [70 80]]


##  6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?
     
###      Demonstrate the case when it is not possible to.

In [17]:


#Defining matrices X & Y
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

#Printing matrices
print("Matrix X:\n", X)
print("Shape of X:", X.shape)
print("\nMatrix Y:\n", Y)
print("Shape of Y:", Y.shape)

#Attempting to multiply X & Y , in this case because the number of columns in X is equal to the number of columns in Y , mutiplication is possible
print("\nAttempting to multiply X @ Y...")
try:
    #Matrix multiplication using the @ operator
    result = X @ Y
    print("Result of X @ Y:\n", result)
except ValueError as e:
    print(f"Error: {e}")

    print("Matrix multiplication is not possible because the number of columns in X (3) must equal the number of rows in Y (3).")

  # Demonstrating a case where mutiplication is not possible , as the number of columns of first matrix is not equal to the number of rows in the second matrix

#Defining matrices A & B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[4, 5], [6, 7]])

#Printing matrices
print("\nMatrix A:\n", A)
print("Shape of A:", A.shape)
print("\nMatrix B:\n", B)
print("Shape of B:", B.shape)

#Attempting to multiply matrices A & B
print("\nAttempting to multiply A @ B...")
try:
    #Matrix multiplication using the @ operator
    result = A @ B
    print("Result of A @ B:\n", result)
except ValueError as e:
    #print(f"Error: {e}")

    print("Matrix mutiplication is not possible because the number of columns in A is 3")
    print("which is not equal to the number of rows in B which is 2")


Matrix X:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Shape of X: (3, 3)

Matrix Y:
 [[4 2]
 [6 2]
 [4 2]]
Shape of Y: (3, 2)

Attempting to multiply X @ Y...
Result of X @ Y:
 [[70 28]
 [70 30]
 [60 26]]

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of A: (3, 3)

Matrix B:
 [[4 5]
 [6 7]]
Shape of B: (2, 2)

Attempting to multiply A @ B...
Matrix mutiplication is not possible because the number of columns in A is 3
which is not equal to the number of rows in B which is 2



## 7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
###      Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
      



In [18]:


# Create arrays x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Original vector x:", x)
print("Original vector y:", y)

#find the shape and no of dimensions of Vector x

shape_x = x.shape
ndim_x = x.ndim
print(f"\nShape of vector x: {shape_x}")
print(f"Number of dimensions of vector x: {ndim_x}")

#reshape the vector x to a matrix of size(3,1)
x_reshaped = x.reshape((3, 1))
print("\nReshaped vector x (3,1):\n", x_reshaped)

#determine the number of dimensions of x after reshaping
ndim_x_reshaped = x_reshaped.ndim
print(f"Number of dimensions of reshaped x: {ndim_x_reshaped}")

#reshape the vector 7 to a matrix of size(3,1)
y_reshaped = y.reshape((3, 1))
print("\nReshaped vector y (3,1):\n", y_reshaped)

#determine the number of dimensions of y after reshaping
ndim_y_reshaped = y_reshaped.ndim
print(f"Number of dimensions of reshaped y: {ndim_y_reshaped}")



Original vector x: [ 2 -1 -8]
Original vector y: [ 3  1 -2]

Shape of vector x: (3,)
Number of dimensions of vector x: 1

Reshaped vector x (3,1):
 [[ 2]
 [-1]
 [-8]]
Number of dimensions of reshaped x: 2

Reshaped vector y (3,1):
 [[ 3]
 [ 1]
 [-2]]
Number of dimensions of reshaped y: 2



## 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.


### NumPy Broadcasting Explained

NumPy's broadcasting is a powerful mechanism that allows operations between arrays with different shapes. When performing arithmetic operations (like addition, subtraction, multiplication, etc.) on arrays of different sizes, NumPy attempts to 'broadcast' the smaller array across the larger array so that they have compatible shapes. This avoids the need for creating explicit copies of arrays to match their dimensions.

**Rules of Broadcasting:**
1.  **Equal dimensions:** If the arrays have different numbers of dimensions, the shape of the one with fewer dimensions is `padded` with ones on its left side.
2.  **Compatible sizes:** For each dimension, the sizes must be either equal, or one of them must be 1.
3.  **Incompatible sizes:** If these conditions are not met, a `ValueError` is raised, indicating that the arrays cannot be broadcast together.

When broadcasting is possible, the smaller array is virtually stretched or copied to match the larger array's dimensions for the operation, but no actual memory is duplicated.

In [19]:


# Create a 3x3 matrix
matrix_3x3 = np.array([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])
print("Original 3x3 Matrix:\n", matrix_3x3)

# --- Demonstration of Subtraction with Broadcasting ---

# Scenario 1: Subtract a scalar
scalar_value = 5
subtraction_scalar = matrix_3x3 - scalar_value
print(f"\nMatrix after subtracting scalar {scalar_value}:\n", subtraction_scalar)

# Scenario 2: Subtract a 1D array (row-wise broadcasting)
# The 1D array [1, 2, 3] will be broadcast across each row of the 3x3 matrix.
row_vector = np.array([1, 2, 3])
subtraction_row = matrix_3x3 - row_vector
print(f"\nMatrix after subtracting row vector {row_vector} (broadcasted row-wise):\n", subtraction_row)

# Scenario 3: Subtract a 1D column array (column-wise broadcasting)
# For column-wise broadcasting, the 1D array needs to be explicitly reshaped to a column vector (3,1).
col_vector = np.array([10, 20, 30]).reshape(3, 1)
subtraction_col = matrix_3x3 - col_vector
print(f"\nMatrix after subtracting column vector:\n", col_vector, "(broadcasted column-wise):\n", subtraction_col)

# --- Demonstration of Multiplication with Broadcasting ---

# Scenario 1: Multiply by a scalar
multiplication_scalar = matrix_3x3 * 2
print("\nMatrix after multiplying by scalar 2:\n", multiplication_scalar)

# Scenario 2: Multiply by a 1D array (row-wise broadcasting)
multiplication_row = matrix_3x3 * row_vector
print(f"\nMatrix after multiplying by row vector {row_vector} (broadcasted row-wise):\n", multiplication_row)

# Scenario 3: Multiply by a 1D column array (column-wise broadcasting)
multiplication_col = matrix_3x3 * col_vector
print(f"\nMatrix after multiplying by column vector:\n", col_vector, "(broadcasted column-wise):\n", multiplication_col)

Original 3x3 Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Matrix after subtracting scalar 5:
 [[ 5 15 25]
 [35 45 55]
 [65 75 85]]

Matrix after subtracting row vector [1 2 3] (broadcasted row-wise):
 [[ 9 18 27]
 [39 48 57]
 [69 78 87]]

Matrix after subtracting column vector:
 [[10]
 [20]
 [30]] (broadcasted column-wise):
 [[ 0 10 20]
 [20 30 40]
 [40 50 60]]

Matrix after multiplying by scalar 2:
 [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]

Matrix after multiplying by row vector [1 2 3] (broadcasted row-wise):
 [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]

Matrix after multiplying by column vector:
 [[10]
 [20]
 [30]] (broadcasted column-wise):
 [[ 100  200  300]
 [ 800 1000 1200]
 [2100 2400 2700]]


# **Part B**

###   1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.

### 1. 2x1+3x2-4x3=6,x1-4x2=8

In [23]:

import sympy

# --- Set 1: 2x1 + 3x2 - 4x3 = 6, x1 - 4x2 = 8 ---

print("--- Set1: 2x1 + 3x2 - 4x3 = 6, x1 - 4x2 = 8 ---")

# Define variables symbolically for clarity in solution
x1, x2, x3 = sympy.symbols('x1 x2 x3')

# Equations in matrix form Ax = b for rank analysis
# A represents the coefficients of x1, x2, x3
A1_rank = np.array([[2, 3, -4],
                    [1, -4, 0]])
# b represents the constants on the right side
b1_rank = np.array([6, 8])

# Augmented matrix for rank check
Ab1_rank = np.concatenate((A1_rank, b1_rank.reshape(-1, 1)), axis=1)

rank_A1 = np.linalg.matrix_rank(A1_rank);
rank_Ab1 = np.linalg.matrix_rank(Ab1_rank);
num_vars1 = A1_rank.shape[1] # Number of variables (x1, x2, x3)

print(f"Matrix A for System 1:\n{A1_rank}")
print(f"Augmented Matrix [A|b] for System 1:\n{Ab1_rank}")
print(f"Rank of coefficient matrix A: {rank_A1}")
print(f"Rank of augmented matrix [A|b]: {rank_Ab1}")
print(f"Number of variables: {num_vars1}")

if rank_A1 != rank_Ab1:
    print("Number of solutions: No solution (inconsistent system)")
elif rank_A1 == num_vars1:
    # This condition typically implies a unique solution if the matrix is square.
    # For an underdetermined system (2 equations, 3 variables), this path won't be taken for x1, x2, x3.
    print("Number of solutions: Unique solution (This scenario is not met as rank < number of variables)")
else: # rank_A1 == rank_Ab1 < num_vars1
    print("Number of solutions: Infinitely many solutions")
    print("Expressing solutions in terms of free variables:")

    # Using sympy to solve the system symbolically
    eq1 = sympy.Eq(2*x1 + 3*x2 - 4*x3, 6)
    eq2 = sympy.Eq(x1 - 4*x2, 8)

    solution = sympy.linsolve([eq1, eq2], (x1, x2, x3))
    print(f"Solution (x1, x2, x3): {solution}")

--- Set1: 2x1 + 3x2 - 4x3 = 6, x1 - 4x2 = 8 ---
Matrix A for System 1:
[[ 2  3 -4]
 [ 1 -4  0]]
Augmented Matrix [A|b] for System 1:
[[ 2  3 -4  6]
 [ 1 -4  0  8]]
Rank of coefficient matrix A: 2
Rank of augmented matrix [A|b]: 2
Number of variables: 3
Number of solutions: Infinitely many solutions
Expressing solutions in terms of free variables:
Solution (x1, x2, x3): {(16*x3/11 + 48/11, 4*x3/11 - 10/11, x3)}


###  2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [28]:
print("\n--- Set 2: 3y1 - 4y2 + 5y3 = 10, -y1 + 2y2 - 4y3 = 8 ---")

# Define variables symbolically
y1, y2, y3 = sympy.symbols('y1 y2 y3')

# Coefficient matrix for y1, y2, y3
A2_rank = np.array([
    [3, -4, 5],
    [-1, 2, -4]
])
# Constant vector
b2_rank = np.array([10, 8])

# Augmented matrix for rank check
Ab2_rank = np.concatenate((A2_rank, b2_rank.reshape(-1, 1)), axis=1)

rank_A2 = np.linalg.matrix_rank(A2_rank)
rank_Ab2 = np.linalg.matrix_rank(Ab2_rank)
num_vars2 = A2_rank.shape[1] # Number of variables (y1, y2, y3)

print(f"Matrix A for System 2:\n{A2_rank}")
print(f"Augmented Matrix [A|b] for System 2:\n{Ab2_rank}")
print(f"Rank of coefficient matrix A: {rank_A2}")
print(f"Rank of augmented matrix [A|b]: {rank_Ab2}")
print(f"Number of variables: {num_vars2}")

if rank_A2 != rank_Ab2:
    print("Number of solutions: No solution (inconsistent system)")
elif rank_A2 == num_vars2:
    print("Number of solutions: Unique solution (This case is unlikely for a 2x3 system)")
else: # rank_A2 == rank_Ab2 < num_vars2
    print("Number of solutions: Infinitely many solutions")
    print("Expressing solutions in terms of free variables:")

    # Using sympy to solve the system symbolically
    eq3 = sympy.Eq(3*y1 - 4*y2 + 5*y3, 10)
    eq4 = sympy.Eq(-y1 + 2*y2 - 4*y3, 8)

    solution2 = sympy.linsolve([eq3, eq4], (y1, y2, y3))
    print(f"Solution: {solution2}")


--- Set 2: 3y1 - 4y2 + 5y3 = 10, -y1 + 2y2 - 4y3 = 8 ---
Matrix A for System 2:
[[ 3 -4  5]
 [-1  2 -4]]
Augmented Matrix [A|b] for System 2:
[[ 3 -4  5 10]
 [-1  2 -4  8]]
Rank of coefficient matrix A: 2
Rank of augmented matrix [A|b]: 2
Number of variables: 3
Number of solutions: Infinitely many solutions
Expressing solutions in terms of free variables:
Solution: {(3*y3 + 26, 7*y3/2 + 17, y3)}
